[workspace]
members = [
    "tealdeer-core",
]
resolver = "2"

[workspace.package]
version = "1.8.1"
authors = [
    "Danilo Bargen <mail@dbrgn.ch>",
    "Niklas Mohrin <dev@niklasmohrin.de>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.85"
homepage = "https://github.com/tealdeer-rs/tealdeer/"
repository = "https://github.com/tealdeer-rs/tealdeer/"

[workspace.dependencies]
anyhow = "1"
app_dirs = { version = "2", package = "app_dirs2" }
clap = { version = "4", features = ["std", "derive", "help", "usage", "cargo", "error-context", "color", "wrap_help"], default-features = false }
env_logger = "0.11"
log = "0.4"
pager = "0.16"
reqwest = { version = "0.12", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
toml = "0.8"
ureq = "3"
yansi = "1"
zip = "5"
